spring:
  main:
    web-application-type: none
  application:
    name: fetch
  docker:
    compose:
      lifecycle-management: start-and-stop
      stop:
        command: down

fever:
  fetch:
    base-url: "https://provider.code-challenge.feverup.com"
    fixed-delay.in.milliseconds: 1000

logging:
  level:
    ROOT: INFO
    com:
      fever: DEBUG

