spring:
  application:
    name: "searchEvents"
  docker:
    compose:
      lifecycle-management: none

logging:
  level:
    ROOT: INFO
    com:
      fever: DEBUG
    org:
      springframework: INFO
